# Generated by Django 5.2.8 on 2026-06-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_aimessageanalysis_id_alter_aireport_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
