# Generated by Django 5.2.8 on 2026-06-16 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_alter_customer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimessageanalysis',
            name='message',
        ),
        migrations.AddField(
            model_name='aimessageanalysis',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.customer'),
        ),
    ]
